name: URLCustomDiscs
main: com.urlcustomdiscs.URLCustomDiscs
version: 2.0.0
api-version: 1.21
author: Asson
commands:
  customdisc:
    description: "Create and play custom music discs from YouTube URLs"
    usage: |
      /customdisc help - Displays the list of commands
      /customdisc create <URL> <disc name> <mono/stereo> - Creates a custom music disc from a Youtube URL
      /customdisc give <disc name> - Gives a custom music disc
      /customdisc list - Displays custom music discs list
      /customdisc delete <disc name> - Deletes a custom music disc
      /customdisc info - Displays custom music disc details in hand
      /execute positioned ~ ~ ~ run playsound minecraft:customdisc.<disc name> ambient @a - Plays a disc (Vanilla)
      /stopsound @a * minecraft:customdisc.<disc name> - Stops a disc (Vanilla)